export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_SINGLE_EMPLOYEE = "FETCH_SINGLE_EMPLOYEE";
export const NEW_EMPLOYEES = "NEW_EMPLOYEES";
export const DELETE_EMPLOYEES = "DELETE_EMPLOYEES";
export const EMPLOYEES_LOADING = "EMPLOYEES_LOADING";
export const FETCH_ALL_HOLIDAYS = "FETCH_ALL_HOLIDAYS";
